pipeline {
    tools {
        maven 'maven'
    }
    agent any
    environment {
        AWS_CRDS = credentials('aws_creds')
        AWS_REGION = credentials('aws_region')
        // CLUSTER_NAME = credentials('clustername')

        KUBECONFIG = '/var/lib/jenkins/.kube/config'
        CHART_PATH = 'helm/vprofile/'
        STAGING_NAMESPACE = 'staging'
        PROD_NAMESPACE = 'production'

        // ECR_REPO_NAME_VPROFILE = credentials('ecr_repo_name_vprofile')
        // ECR_REPO_URI_VPROFILE = credentials('ecr_repo_uri_vprofile')

        GITHUB_TOKEN = credentials('github')
        DOCKER_IMAGE_NAME = 'vanthiyadevan/vprofile'
    }
    stages {
        stage('Installing Dependencies') {
            options { timestamps() }
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }

        stage('Unit Test') {
            steps {
                script {
                    sh "mvn test"
                }
            }
            // post {
            //     always {
            //         junit '**/target/surefire-reports/*.xml'
            //     }
            // }
        }
        
        stage('Checkstyle Analysis') {
            steps {
                sh 'mvn checkstyle:checkstyle'
            } 
        }

        stage('sonarQube') {
            steps {
                script {
                    withSonarQubeEnv('sonar-scanner') {
                        sh '''
                            mvn sonar:sonar \
                            -Dsonar.projectKey=vprofile \
                            -Dsonar.projectName=vprofile \
                            -Dsonar.projectVersion=1.0 \
                            -Dsonar.sources=src/main/java \
                            -Dsonar.tests=src/test/java \
                            -Dsonar.java.binaries=target/classes
                        '''
                    }
                }
            }
        }

        // stage('Quality Gate') {
        //     steps {
        //         script {
        //             timeout(time: 2, unit: 'MINUTES') {
        //                 waitForQualityGate abortPipeline: true
        //             }
        //         }
        //     }
        // }

        stage('Docker Build'){
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} -f Dockerfile ."
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', 
                        passwordVariable: 'DOCKER_PASSWORD', 
                        usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                        sh "docker push ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
                    }
                }
            }
        } 

        stage ('Deploy to Staging') {
            steps {
                script {
                    sh "helm upgrade --install vprofile ${CHART_PATH} \
                    --namespace ${STAGING_NAMESPACE} \
                    --set appimage=${DOCKER_IMAGE_NAME},apptag=${BUILD_NUMBER}"
                }
            }
        }         
    }
}
